SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: download_file_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.download_file_data (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    directory_name character varying(255),
    path_preview_image_file character varying(255),
    path_video_file character varying(255),
    uuid character varying(255)
);


ALTER TABLE public.download_file_data OWNER TO postgres;

--
-- Name: download_file_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.download_file_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.download_file_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upload_file_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.upload_file_data (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    original_name character varying(255),
    path character varying(255),
    uuid character varying(255)
);


ALTER TABLE public.upload_file_data OWNER TO postgres;

--
-- Name: upload_file_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.upload_file_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upload_file_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upload_file_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.upload_file_status (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    path character varying(255),
    status character varying(255),
    uuid character varying(255)
);


ALTER TABLE public.upload_file_status OWNER TO postgres;

--
-- Name: upload_file_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.upload_file_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upload_file_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: download_file_data download_file_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.download_file_data
    ADD CONSTRAINT download_file_data_pkey PRIMARY KEY (id);


--
-- Name: upload_file_data upload_file_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.upload_file_data
    ADD CONSTRAINT upload_file_data_pkey PRIMARY KEY (id);


--
-- Name: upload_file_status upload_file_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.upload_file_status
    ADD CONSTRAINT upload_file_status_pkey PRIMARY KEY (id);